//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran2016.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOST
    {
        public GOST()
        {
            this.PRIJATELJIs = new HashSet<PRIJATELJI>();
            this.PRIJATELJIs1 = new HashSet<PRIJATELJI>();
            this.REZERVACIJAs = new HashSet<REZERVACIJA>();
        }
    
        public string EMAIL_GOSTA { get; set; }
        public string PASS_GOSTA { get; set; }
        public string IME_GOSTA { get; set; }
        public string PREZIME_GOSTA { get; set; }
        public string POL_GOSTA { get; set; }
        public bool MAIL_POTVRA { get; set; }
        public string CPASS_GOSTA { get; set; }
        public byte[] SLIKA { get; set; }
    
        public virtual ICollection<PRIJATELJI> PRIJATELJIs { get; set; }
        public virtual ICollection<PRIJATELJI> PRIJATELJIs1 { get; set; }
        public virtual ICollection<REZERVACIJA> REZERVACIJAs { get; set; }
    }
}
