//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran2016.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    
    public partial class GOST
    {
        public GOST()
        {
            this.PRIJATELJIs = new HashSet<PRIJATELJI>();
            this.PRIJATELJIs1 = new HashSet<PRIJATELJI>();
            this.REZERVACIJAs = new HashSet<REZERVACIJA>();
        }
       
        [Required(ErrorMessage = "Email je obavezan")]
        [DisplayName("Email")]
        public string EMAIL_GOSTA { get; set; }
        [Required(ErrorMessage = "Lozinka je obavezna")]
        [DisplayName("Lozinka")]
        [DataType(DataType.Password)]
        public string PASS_GOSTA { get; set; }
        [Required(ErrorMessage = "Ime je obavezno")]
        [DisplayName("Ime")]
        public string IME_GOSTA { get; set; }
        [Required(ErrorMessage = "Prezme je obavezno")]
        [DisplayName("Prezime")]
        public string PREZIME_GOSTA { get; set; }
        [Required(ErrorMessage = "Pol je obavezan")]
        [DisplayName("Pol")]
        [RegularExpression(@"^[mMzZ]$", ErrorMessage = "dozvoljene vrednosti su 'M' i 'Z' ")]
        public string POL_GOSTA { get; set; }
        public bool MAIL_POTVRA { get; set; }
        [Required(ErrorMessage = "Potvrdna lozinke je obavezna")]
        [DisplayName("Potvrda lozinke")]
        [DataType(DataType.Password)]
        [Compare("PASS_GOSTA", ErrorMessage = "Lozinke se ne poklapaju.")]
        public string CPASS_GOSTA { get; set; }
        public byte[] SLIKA { get; set; }
    
        public virtual ICollection<PRIJATELJI> PRIJATELJIs { get; set; }
        public virtual ICollection<PRIJATELJI> PRIJATELJIs1 { get; set; }
        public virtual ICollection<REZERVACIJA> REZERVACIJAs { get; set; }
    }
}
