//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran2016.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    public partial class JELOVNIK
    {
        [DisplayName("ID restorana")]
        public string ID_RESTORANA { get; set; }
        public string ID_JELA { get; set; }
        [Required(ErrorMessage = "Naziv jela je obavezan")]
        [DisplayName("Naziv jela")]
        public string NAZIV_JELA { get; set; }
        [Required(ErrorMessage = "Vrsta je obavezna")]
        [DisplayName("Vrsta")]
        public string OPIS { get; set; }
        [Required(ErrorMessage = "Cena je obavezna")]
        [DisplayName("Cena")]
        public decimal CENA_JELA { get; set; }
    
        public virtual RESTORAN RESTORAN { get; set; }
    }
}
