//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran2016.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENADZER
    {
        public string IDMENADZERA { get; set; }
        public string ID_RESTORANA { get; set; }
        public string ASD { get; set; }
    
        public virtual RESTORAN RESTORAN { get; set; }
    }
}
