//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran2016.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIJATELJI_REZERVACIJA
    {
        public string EMAIL_GOSTA1 { get; set; }
        public string EMAIL_GOSTA { get; set; }
        public int ID { get; set; }
        public Nullable<int> OCENA { get; set; }
    
        public virtual PRIJATELJI PRIJATELJI { get; set; }
        public virtual REZERVACIJA REZERVACIJA { get; set; }
    }
}
