//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran2016.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class RESTORAN
    {
        public RESTORAN()
        {
            this.JELOVNIKs = new HashSet<JELOVNIK>();
            this.MENADZERs = new HashSet<MENADZER>();
            this.STOes = new HashSet<STO>();
        }
    
        public string ID_RESTORANA { get; set; }
        public string NAZIV_RESTORANA { get; set; }
        public string ADRESA_RESTORANA { get; set; }
        public string MAIL_RESTORANA { get; set; }
        public string TELEFON_RESTORANA { get; set; }
        [DisplayFormat(DataFormatString = "{0:n2}", ApplyFormatInEditMode = true)]
        public float PROSECNA_OCENA { get; set; }
        public string OPIS_RESTPRANA { get; set; }
        public Nullable<float> LATITUDA { get; set; }
        public Nullable<float> LONGITUDA { get; set; }
        public Nullable<int> BROJ_KOLONA { get; set; }
    
        public virtual ICollection<JELOVNIK> JELOVNIKs { get; set; }
        public virtual ICollection<MENADZER> MENADZERs { get; set; }
        public virtual ICollection<STO> STOes { get; set; }
    }
}
