//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran2016.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    public partial class STO
    {
        public STO()
        {
            this.REZERVACIJAs = new HashSet<REZERVACIJA>();
        }
    
        public string ID_RESTORANA { get; set; }
        public string ID_STOLA { get; set; }
        public int BR_STOLICA { get; set; }
    
        public virtual RESTORAN RESTORAN { get; set; }
        public virtual ICollection<REZERVACIJA> REZERVACIJAs { get; set; }
    }
}
